name: Deploy to Heroku
on:
  pull_request:
    types: [closed]
    branches:
      - "main"
jobs:
  build:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    environment: production
    if: github.event.pull_request.merged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up credencials and Deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          procfile: "web: npm start"
